### ISSUE TITLE
core/Symbol documentation doesn't render correctly.

### ISSUE THREAD

**Issue by rg-3** [docmeta/rubydoc.info#117]
Creating a new issue from https://github.com/lsegal/yard/issues/1114:

> The class description is not being parsed correctly on this page:
http://www.rubydoc.info/stdlib/core/Symbol
I didn't test locally with Ruby's source.

**Comment by lsegal** [comment]
Closing out this old issue due to inactivity. There's not _much_ we can do about documentation formatting issues with core Ruby classes that don't use standardized syntax. It seems like this is more of a bug in string.c documentation than YARD itself.

That said, we should probably update our stdlib hosted packages since this may have been fixed in Ruby.
