### ISSUE TITLE
Intermittent 503 errors on rubydoc.info

### ISSUE THREAD

**Issue by floehopper** [docmeta/rubydoc.info#134]
Hi there. Like many Rubyists I've come to rely on the excellent [rubydoc.info website](https://rubydoc.info/) for documentation for many Ruby gems. However, in recent weeks I've seen a lot of 503 errors. Do you know what the problem is? If there's anything I can do to help, please let me know. Thanks again for the great website!

**Comment by adam12** [comment]
Loren just recently announced on Twitter that Varnish looked to be the culprit, and it's been disabled for the last couple days and the 503's seem to have been greatly reduced. I've tested many of the larger gems on the site and everything seems to be a lot more stable (albeit the sidebar having a slightly slower perceived load time).

It was mentioned there was hope to bring Varnish back into the rubydoc.info stack but the reason for the 503's would have to be determined before that could be the case.

**Comment by floehopper** [comment]
Thanks for the update.

**Comment by lsegal** [comment]
Closing this out since we've done a bit of work to improve this in the last month. We still might have a few remaining 503s but tl;dr is we're keeping a close eye on this and things should have improved significantly from this original report.

That said, please let us know if you see persisting 503s that aren't being fixed.

**Comment by floehopper** [comment]
Thanks! 👍
