### ISSUE TITLE
Brainstorming: the interface to rubydoc.info and custom tags and macros.

### ISSUE THREAD

**Issue by dogweather** [docmeta/rubydoc.info#92]
**My use case**

Generating docs for attributes with validations:

``` ruby
attr_accessor :municipality_name
validates     :municipality_name, presence: true, type: String
```

I think I can do this entirely with Yard macros and custom tag CLI options — no Ruby needed. The result will be:

``` ruby
# @required Yes
# @returns [String]
```

...where `@required` is set up as a name-tag:

``` bash
yardoc --name-tag required:Required
```

**It'd be cool if these would appear on rubydoc.info**

Is this possible? Is there some kind of interface (`.yardopts` ?) which rubydoc.info reads and will use for customizations like these? 

I can see that generating my own docs which I host will work fine. But I'd also like my additional metadata to appear on rubydoc.info.

Thanks for any feedback.

**Comment by lsegal** [comment]
Rubydoc uses your .yardopts file, so anything you put in there will work. We will *not* execute custom code (ruby files) or plugins that are not already whitelisted for usage, but you should not need that in your case.

**Comment by dogweather** [comment]
Awesome! Excellent. Do you have a pointer to the currently whitelisted plugins?

**Comment by lsegal** [comment]
Our Gemfile lists all plugins we use. White listing would involve adding it there.

**Comment by lsegal** [comment]
Closing out this old issue due to inactivity. If this report is related to a production issue on rubydoc.info, it is very likely that the issue has since been resolved. If the issue is still persisting, feel free to comment or file an updated issue.

As a sidenote, RubyDoc.info now supports running plugins or local extension files during code parsing without the need to whitelist.
